### ISSUE TITLE
Folder structure problem

### ISSUE THREAD

**Issue by haowang1013** [sideeffects/HoudiniNiagara#10]
Hi,

Right now the root of this repo is at the project/engine level, this makes it impossible to be added as a sub-module to existing projects. It would be nice if the root of the repo to be changed to "Plugins/FX/HoudiniNiagara" which would fix this problem - see example from the "HoudiniEngineForUnreal" plugin.

**Comment by dpernuit** [comment]
Hi,
The latest update should have fixed this issue.
