### ISSUE TITLE
Engine modules cannot be compiled at runtime.

### ISSUE THREAD

**Issue by flicker8210** [sideeffects/HoudiniNiagara#11]
Hello.
I encountered a problem. When using version 1.0 of HoudiniNiagara, the new spawn particles from houdini point cache will report an error: "Input has an invalid type:Module.Houdini.PointCache;The input Module .Houdini.PointCache on function SpawnParticlesFromHoudiniPointCache has a type which is invalid.The type of this input likely doesn't exist anymore.This input must be fixed in the script before this module can be used."
When using HoudiniNiagara version 2.0, an error will be reported directly when opening the project: "The following modules are missing or built with a different engine version:
HoudiniNiagara
HoudiniNiagaraEditor
Would you like to rebuild them now?"
My current ue4 version is 4.25.3.

**Comment by flicker8210** [comment]
My problem was solved. The plug-in package I downloaded directly supports ue4.24, but I mistakenly thought it supported ue4.25. After finding the correct plug-in, there were no such errors.
Thank you all.

**Comment by dpernuit** [comment]
Hi,
Glad you fixed the issue. Yes, the newer version of the plugin (that uses the point cache) is only for 4.25.
