### ISSUE TITLE
Build Cook Fail 4.25

### ISSUE THREAD

**Issue by stylerm** [sideeffects/HoudiniNiagara#15]
Using the HoudiniNiagara v2 Plugin I wasnt sure if it was shippable but we experienced a build fail came up with the error pointing at the Point Cache module 

On a build it failed on the **Spawned Particles from Houdini Point Cache** Module, came up with 
`
LogInit: Display: LogNiagaraEditor: Error: Pin states that it is of class type, but is missing its class object. This is usually the result of a registered type going away. Pin Name 'None' Owning Node 'NiagaraNodeParameterMapGet_6'.`

**Comment by nanocell** [comment]
Sorry for the long wait! This should now be fixed by d1ada6b306a62169c5bfd90a47711c8b8ac334f7.
