### ISSUE TITLE
Attributes Aren't Relayed? (when there are zero points on frame #1)

### ISSUE THREAD

**Issue by AtomicPerception** [sideeffects/HoudiniNiagara#16]
I'm generating a series of points, advection from a pyro source. The concept is dragon breath. This means the points aren't there on frame #1, the emitter gets turned on down the line, turned off, then turned on again.
What seems to be happening is that this Niagara plugin is looking for attributes on the first frame of the timeline. In my case, there are zero points. When this occurs, a decision is made to assume that there are no attributes and only @id and @P are exported. This is wrong, I have Cd on my points which appear on frame #255.

Attribute detection should occur only when points are present. The timeline should be scanned first, attributes determined, then the export should begin.

I can "trick" the system by switching in a single point with all my attributes and hiding that behind my camera, but I shouldn't have to do that.

**Comment by nanocell** [comment]
Hi,

I have been unable to reproduce this issue using the latest Niagara ROP (`labs::niagara_rop::2.0`) and Houdini 19.0.426. If you are still experiencing this issue please upload a .hip file (or send to support@sidefx.com) that we can use to further investigate this issue.
