### ISSUE TITLE
4.26 version

### ISSUE THREAD

**Issue by simco50** [sideeffects/HoudiniNiagara#17]
Now that UE4.26 is released, it would be really good to have an updated version.
I see that Epic has just removed this plugin in 4.26 likely for compatibility reasons but it's problematic for projects updating the engine that are dependent on this plugin.

Thanks

**Comment by jbrd** [comment]
We'd find this useful too!

**Comment by NNois** [comment]
Yes please ;-) a recompile for 4.26 !
