### ISSUE TITLE
Can anyone update build to 4.26.1 thanks

### ISSUE THREAD

**Issue by superdude12399** [sideeffects/HoudiniNiagara#18]
Can anyone make a prebuild 4.26.1 version, thanks.

**Comment by dangerstudios** [comment]
yes please! :) I updated my engine to 4.26.1 now the plugin won't load :(

**Comment by dpernuit** [comment]
Hi,
Are you using the latest 4.26 binaries? The latest binaries on the release page should work just fine with 4.26.1.
Just tried on my side with a fresh 4.26.1 and the plugin loads fine.
