### ISSUE TITLE
can't compile with ue5, please provided a binary for ue5

### ISSUE THREAD

**Issue by ChildAdrian** [sideeffects/HoudiniNiagara#21]
I create a new uproject and put the source into "Plugins/FX", and the error message says it couldn't be compiled.
it will be appreciate if a prebuild binary for ue5 is provided.

**Comment by nanocell** [comment]
Sorry for the long delay! The latest UE5_EA branch should work for UE5 Early Access. Here is also a brand new release binary that you can use: https://github.com/sideeffects/HoudiniNiagara/releases/tag/v2.2.0-UE5.00_EA.
