### ISSUE TITLE
Reimport bug

### ISSUE THREAD

**Issue by Yamjin** [sideeffects/HoudiniNiagara#26]
When HoudiniPointCache aseet is reimported, an error occured.
When the asset is used by Actor (Niagara system asset of Niagara particle system component) on opened level, the error occured. (When the asset is not used on opened level, not occured.)

Using: Houdini Niagara Plugin v2.2.0 - UE4.26.2

```
Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/RenderCore/Private/RenderResource.cpp] [Line: 149] A FRenderResource was deleted without being released first!

UE4Editor_RenderCore
UE4Editor_HoudiniNiagara!FHoudiniPointCacheResource::`scalar deleting destructor'()
UE4Editor_HoudiniNiagara!UHoudiniPointCache::~UHoudiniPointCache()
UE4Editor_HoudiniNiagara!UHoudiniPointCache::`vector deleting destructor'()
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_HoudiniNiagaraEditor!UHoudiniPointCacheFactory::FactoryCreateFile() [(delete)\Plugins\HoudiniNiagara\Source\HoudiniNiagaraEditor\Private\HoudiniPointCacheFactory.cpp:74]
UE4Editor_UnrealEd
UE4Editor_HoudiniNiagaraEditor!UHoudiniPointCacheFactory::Reimport() [(delete)\Plugins\HoudiniNiagara\Source\HoudiniNiagaraEditor\Private\HoudiniPointCacheFactory.cpp:173]

```

Thanks

**Comment by nanocell** [comment]
Hi Yamin,

I have not been able to reproduce this issue using the latest source in the UE4.26 branch (the issue has possibly been fixed in the mean time). If you are still having this issue using the latest source, please send an HBJSON file that we can use for further investigation.
