### ISSUE TITLE
ue5.2 

### ISSUE THREAD

**Issue by samrat333** [sideeffects/HoudiniNiagara#43]
please update 5.2 preview 2

**Comment by samrat333** [comment]
we trayed many to build it but failed every time

**Comment by samrat333** [comment]
please update source file for ue 5.2

**Comment by SethPDA** [comment]
Tried building for 5.2 too, but fails. I would be very happy if someone would build it, or at least provide with info on how to build this. There are a bunch of errors that come up at building.

**Comment by KMStu** [comment]
I fixed this for us internally at Epic, but I can't contribute the code back here as I'm not a contributor to the project.
Happy to provide the changes.

**Comment by KMStu** [comment]
https://github.com/sideeffects/HoudiniNiagara/pull/44 is the pull request to fix the compile issues, and update the DI to RDG.

**Comment by OptimisticMonkey** [comment]
Thank you @KMStu !  Integrating this now :-)

**Comment by samrat333** [comment]
> #44 is the pull request to fix the compile issues, and update the DI to RDG.

we try to build https://github.com/KMStu/HoudiniNiagara/tree/UE5.20 your build failed evey time

**Comment by OptimisticMonkey** [comment]
@samrat333 There is a new 5.2 branch as well as 5.2 binary release.  
[https://github.com/sideeffects/HoudiniNiagara/releases/tag/v2.4.0-UE5.2](https://github.com/sideeffects/HoudiniNiagara/releases/tag/v2.4.0-UE5.2)

Let me know if you still have issues.
