### ISSUE TITLE
ue 5.3

### ISSUE THREAD

**Issue by samrat333** [sideeffects/HoudiniNiagara#49]
not compile with ue 5.3 vs 2023 community

**Comment by dpernuit** [comment]
Tomorrow's daily build of the plugin should work with UE5.3

**Comment by BrutalT69** [comment]
Upload soon guys, whole life depending on this plugin.

**Comment by BrutalT69** [comment]
not working with 5.3 at all

**Comment by dpernuit** [comment]
The latest release version should build fine with 5.3. - and binaries are available.
