### ISSUE TITLE
P_on_surface.uasset is corrupt in 5.4 branch 

### ISSUE THREAD

**Issue by resinbeard** [sideeffects/HoudiniNiagara#55]
On branch UE5.4
Recently built Unreal 5.4.1 on Linux
Using Linux Houdini 20.0.688

When packaging for Linux, receiving:
`LoadErrors: Error: Unable to load package '/HoudiniNiagara/PointCache/P_on_surface'. The end of package tag is not valid. Check that the file is of the expected type and not corrupted.`

This seems like a pretty widespread issue affecting other users and releases of this plugin. 
Could we get an non-corrupted version of this binary?

For now, removing the file helped me move along with packaging. Crossing my fingers that it doesn't bite me down the line.

Appreciate your team's hard work on this!

Best,
Murray

**Comment by SteamToStream** [comment]
I encountered the same issue when packaging Windows packages using version 5.2, but I replaced the error file with the same file from the 5.0 plugin. After that, I stopped reporting errors but received some warnings. Like this, "\ Plugins \ HoudiniNiagara \ Content \ PointCache \ P_on_surface. uasset: Asset has been saved with empty engine version. The asset will be loaded but may be incompatible." But after packaging, I can see the particle effect. I hope this can help you!

**Comment by dpernuit** [comment]
Hi,

Yes, we're aware of the issue - and I reimported the asset recently.
But unfortunately, I'm having issues updating it here on Git.. 

I just put a new release on the repo here - the zipped binaries have a fixed version of the uasset.
